---
title: "View Details of Template-Based Application"
keywords: "Kubernetes, {ks_product}, Project Management, Application, View Details of Template-Based Application"
description: "Describes how to view details of template-based applications."
weight: 05
---


:ks_permission: **Application Instance View**
:ks_navigation: **Application Workloads > Applications**


This section describes how to view details of a template-based application.


== Prerequisites

:relfileprefix: ../../../../

include::../../../../_custom/projectManagement/projectManagement-prer-requiredPermission_v42.adoc[]

:relfileprefix: ./



== Steps

include::../../../../_custom/workspaceManagement/workspaceManagement-oper-openWorkspacePage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../../_custom/projectManagement/projects-oper-dropdownList.adoc[]

+

. On the **Applications** page, click the name of an application to open its details page.

. On the application details page, view the application's resource attributes in the **Attributes** area.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Cluster
|The cluster to which the application belongs.

|Project
|The project to which the application belongs.

include::../../../../_custom/projectManagement/apps/apps-para-status_v4.adoc[]

|Application
|The application template used by the application.

include::../../../../_custom/projectManagement/apps/apps-para-details2.adoc[]
|===
--

+

include::../../../../_custom/projectManagement/apps/apps-oper-viewResourceStatus_v42.adoc[]

+

. On the application details page, click **Application Template** to view the application template information.
+
--
* Click **Application Description** to view the introduction information of the application.

* Click **Chart Files** to view the files in the Helm Chart archive. Click the drop-down list on the right side of **Chart Files** to select the file you want to view. Click image:/images/ks-qkcp/zh/icons/download-dark-white.svg[download,18,18] to download the file to your local machine.
--

. On the application details page, click **Application Settings** to view the application's configuration information.
+
--
// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

The application's default settings are saved in the **values.yaml** file within the Helm Chart archive. The **Application Settings** page displays the customized settings configured by the user during application installation.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--