---
title: "Configuring Extensions"
keywords: "Kubernetes, {ks_product}, Settings, Configuration, Extensions"
description: "Describes how to configure extensions."
weight: 01
---

This section describes how to configure extensions.

In addition to configuring an extension during its installation, you can also modify an extension's configuration on its details page in the Extensions Center.

[.admon.attention,cols="a"]
|===
|Note

|Configuration changes are not allowed during installation, upgrade, or uninstallation processes.
|===

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].
* You have successfully installed an extension.

== Steps

include::../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center**.
. Click the name of an installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] under the extension icon and select **Extension Configuration**.

. Enter the configuration you need in the middle **Custom Configuration** box. After reviewing the **Final Configuration**, click **OK**.
+
--
// * Click image:/images/ks-qkcp/zh/icons/maximize.svg[maximize,18,18] in the upper right corner to view the configuration information in full screen. Full screen is not required.

* Click image:/images/ks-qkcp/zh/icons/upload.svg[upload,18,18] to upload a custom configuration file.

* Click image:/images/ks-qkcp/zh/icons/copy-light.svg[copy-light,18,18] to copy the configuration information.

* Click image:/images/ks-qkcp/zh/icons/download-new.svg[download-new,18,18] to download the configuration file.
--