---
title: "Configuring Cluster Agent"
keywords: "Kubernetes, {ks_product}, Settings, Configuration, Cluster Agent"
description: "Describes how to configure the cluster agent."
weight: 02
---

This section describes how to configure the cluster agent.

In addition to configuring the cluster agent during extension installation, you can also modify the cluster agent configuration on the extension details page in the Extensions Center.

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].
* You have successfully installed an extension configured with a cluster agent.

== Steps

include::../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center**.
. Click the name of the installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] under the extension icon and select **Cluster Agent Configuration**.
. Select a cluster and click **Next**.
. On the **Differentiated Configuration** tab, click image:/images/ks-qkcp/zh/icons/pen-light.svg[pen-light,18,18] to edit the agent configuration for the cluster.

. Enter the configuration you need in the middle **Custom Configuration** box. After reviewing the **Final Configuration**, click **OK**.
+
--
* Click the image:/images/ks-qkcp/zh/icons/maximize.svg[maximize,18,18] in the upper right corner to view the configuration information in full screen.

* Click image:/images/ks-qkcp/zh/icons/upload.svg[upload,18,18] to upload a custom configuration file.

* Click image:/images/ks-qkcp/zh/icons/copy-light.svg[copy-light,18,18] to copy the configuration information.

* Click image:/images/ks-qkcp/zh/icons/download-new.svg[download-new,18,18] to download the configuration file.
--