---
title: "Disable an Extension"
keywords: "Kubernetes, {ks_product}, Enable, Disable, Extension"
description: "Describes how to disable an extension."
weight: 04
---

This section describes how to disable an extension.

After an extension is installed, it is automatically enabled. You can disable an extension on its details page in the Extensions Center.

After disabling, you can enable it again to continue using the extension in clusters, workspaces, and projects.

== Prerequisites

You need to have the **platform-admin** role in the KubeSphere platform. For more information, see link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

include::../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center** to go to the Extensions Center page.
. Click the name of an installed extension to go to its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] under the extension icon and select **Disable**.
. After disabling, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] again and select **Enable** to continue using the extension.