---
title: "Component Dock"
keywords: "Kubernetes, {ks_product}, Component Dock, Quick Access"
description: "Introduces how to use the Component Dock."
weight:  02
---

The Component Dock is the global access point for platform management components, extensions, and toolboxes. You can also customize component entries in the Component Dock to add them to the top navigation bar for quick access.

== Prerequisites

You have obtained the username and password for the KubeSphere web console.

== Steps

. Log in to the KubeSphere web console.

. Click **Component Dock**. On the Component Dock page, click any icon to access the corresponding page.

. Click **Component Dock > Customize Component Entry**, then click the dot below each icon to select the components you want to add to the top navigation bar.

. At the top of the page, drag to adjust the order of the components.

. Click **Save Plan**, then close the Component Dock page. The components will be available for quick access in the top navigation bar.

. To remove a component from the top navigation bar, click **Component Dock > Customize Component Entry**, deselect the component, and click **Save Plan**.