// :ks_include_id: 5b3a15eedffe4ef39e6a46e6adc2b335
. In the **Create Custom Monitoring Dashboard** dialog box, set the name, description, and template for the monitoring dashboard, then click **Next**.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Name
|The name of the custom monitoring dashboard. The name can only contain lowercase letters, numbers, and hyphens (-), must start and end with a lowercase letter or number, and can be up to 63 characters long.

|Description
|The description of the custom monitoring dashboard. The description can contain any characters and can be up to 256 characters long.

|Template
|The template for the custom monitoring dashboard.

* KubeSphere provides templates with pre-configured custom monitoring dashboards for Elasticsearch, MySQL, Redis, Jenkins, and GPU. Each template provides some pre-configured monitoring metrics and charts, which you can customize based on the template to reduce operations.

* To use a Grafana monitoring dashboard, you need to upload a Grafana monitoring dashboard configuration file.

* You can also select **Custom** to use an empty template.
|===
--

. On the custom monitoring dashboard editing page, set up monitoring charts and text-based monitoring metrics as needed.
+
====
* On the left side of the page, click image:/images/ks-qkcp/zh/icons/add-dark.svg[add-dark,18,18], set the metric parameters, then click image:/images/ks-qkcp/zh/icons/check-dark.svg[check-dark,18,18] to create a text-based monitoring metric.
+
--
include::customMonitoringDashboards-para-textMetric.adoc[]
--

* In the lower right corner of the page, click **Add Monitoring Item**, select **Line Chart** or **Bar Chart**, set the chart parameters, then click image:/images/ks-qkcp/zh/icons/check-dark.svg[check-dark,18,18] to create a monitoring chart.
+
--
include::customMonitoringDashboards-para-monitoringChart.adoc[]
--
====

. In the upper right corner of the page, click **Save Template**. After the monitoring dashboard is created, it will be displayed in the custom monitoring dashboard list.