// :ks_include_id: 1762c0ce44e445d89cd9f2e5b34055fa
. In the list, click the name of a custom monitoring dashboard to open it. Then, in the upper-right corner of the page, click **Edit Template**.

. On the left side of the page, configure monitoring metrics displayed as text.
+
====
* Click image:/images/ks-qkcp/zh/icons/add-dark.svg[add-dark,18,18] to add a monitoring metric.
+
--
include::customMonitoringDashboards-para-textMetric.adoc[]
--

* Hover your mouse over a monitoring metric, then click image:/images/ks-qkcp/zh/icons/trash-dark.svg[trash-dark,18,18] to delete the monitoring metric.

* Hover your mouse over a monitoring metric, then click image:/images/ks-qkcp/zh/icons/pen-dark.svg[pen-dark,18,18] to edit the monitoring metric.
====

. In the monitoring chart list on the right side of the page, configure monitoring charts.
+
====
* Click **Add Monitoring Item** to add a monitoring chart.
+
--
include::customMonitoringDashboards-para-monitoringChart.adoc[]
--

* Hover your mouse over a monitoring chart name, then click image:/images/ks-qkcp/zh/icons/trash-light.svg[trash-light,18,18] to delete the monitoring chart.

* Hover your mouse over a monitoring chart name, then click image:/images/ks-qkcp/zh/icons/pen-light.svg[pen-light,18,18] to edit the monitoring chart.

* Drag the image:/images/ks-qkcp/zh/icons/drag-handle.svg[drag-handle,18,18] on the right side of the monitoring chart name to adjust the order of monitoring charts.
====

. In the upper-right corner of the page, click **Save Template** to complete the editing.