---
title: "View Composed App Details"
keywords: "Kubernetes, {ks_product}, Project Management, App, View Composed App Details"
description: "Describes how to view composed app details."
weight: 05
---

:ks_permission: ** Service Mesh View**
:ks_navigation: **Grayscale Release > Composed Apps**


This section describes how to view composed app details.


== Prerequisites


:relfileprefix: ../../../../

include::../../../../_custom/projectManagement/projectManagement-prer-requiredPermission_v42.adoc[]

:relfileprefix: ./



== Steps

include::../../../../_custom/workspaceManagement/workspaceManagement-oper-openWorkspacePage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../../_custom/projectManagement/projects-oper-dropdownList.adoc[]

+

. On the **Composed Apps** page, click the name of an app to open its details page.

. On the app details page, view the resource attributes of the app in the **Attributes** area.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

include::../../../../_custom/projectManagement/apps/apps-para-details1.adoc[]

include::../../../../_custom/projectManagement/apps/apps-para-details2.adoc[]

|App Governance
|Whether app governance is enabled for the app. After app governance is enabled, you can use traffic monitoring, grayscale release, and tracing features.
|===
--

+

include::../../../../_custom/projectManagement/apps/apps-oper-viewResourceStatus.adoc[]

+

. On the app details page, click **Traffic Monitoring** to view the traffic information of the app.
+
--
Click a service in the graph panel, and on the right side of the page, view the traffic monitoring information and related pod information of the service, and perform **Traffic Management**.

[%header,cols="1a,4a"]
|===
|Parameter |Description

|Traffic Policy > Load Balancing
|Load balancing algorithm

* **Round Robin**: Sends client requests to backends in turn.
* **Least Request**: Randomly selects two healthy backends and sends client requests to the backend with fewer requests.
* **Random**: Sends client requests to a random healthy backend.
* **Pass Through**: Forwards connections directly to the original IP address requested by the caller without any form of load balancing. Used for advanced configuration. Use with caution.

|Traffic Policy > Session Persistence
|
Maps requests to backend servers based on specific identifiers (such as HTTP headers, cookies, query parameters, etc.) to achieve balanced distribution and load sharing of requests.

* **Hash based on HTTP Header**: Hash based on a specific HTTP header.
* **Hash based on HTTP Cookie**: Hash based on an HTTP cookie.
* **Hash based on HTTP Query Parameter**: Hash based on a specific HTTP query parameter.
* **Hash based on Source IP Address**: Hash based on the source IP address. Applicable to TCP and HTTP connections.
* **Hash based on ring/modulo**: The ring/modulo hash load balancer uses a consistent hashing algorithm to hash backend hosts.
* **Hash based on Maglev**: The Maglev hash load balancer uses a consistent hashing algorithm to hash backend hosts.

For more information, refer to link:https://istio.io/v1.16/zh/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB[this document].

|Connection Pool
|Creates a fixed number of connection objects for the application and stores them in a connection pool for reuse. Each request obtains a connection object from the pool and returns it to the pool after use.

After enabling, you need to set the maximum number of connections, maximum requests per connection, maximum retries, connection timeout, maximum request quantity, and maximum pending request quantity.

|Circuit Breaker
|If a service is inaccessible and meets specified conditions, the circuit breaker marks the service as unavailable and directly returns an error response to the client within a specified time range.

After enabling, you need to set the consecutive 5XX error count, check interval (seconds), maximum ejection percentage (%), and ejection time (seconds).
|===

--

. On the app details page, click **Grayscale Release** to view the grayscale release information of the app. For more information, refer to link:../../02-grayscale-release/[Grayscale Release].
+
--
// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

To use the **Traffic Monitoring** and **Grayscale Release** features, you need to enable the app governance feature when creating the composed app. For more information, refer to link:../03-manually-compose-an-app/[Create a Composed App].

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

. On the app details page, click **Tracing** to view the request tracing information of the app.
+
--
// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

* To use the **Tracing** feature, you need to enable the app governance feature when creating the composed app. For more information, refer to link:../03-manually-compose-an-app/[Create a Composed App].

* You also need to enable the project gateway and enable the **Tracing** feature for the project gateway. For more information, refer to link:../../../12-gateway/01-project-gateway/01-enable-a-project-gateway[Enable a Project Gateway].

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--