---
title: "User and Role Management"
keywords: "Kubernetes, {ks_product}, Access Control, User, Role"
description: "Introduces how to control platform access permissions."
weight: 05
icon: "/images/docs/common/docs.svg"
layout: "second"
---


KubeSphere is a multi-tenant container management platform. Like Kubernetes, it controls user permissions through Role-Based Access Control (RBAC) to achieve logical resource isolation.

Resources in KubeSphere are divided into four levels: **Platform, Workspace, Cluster, and Project**. All resources belong to these four resource levels, and each level can control user resource access permissions through roles. Each level has multiple built-in roles by default, and you can also create roles with custom permissions.

The workspace, as the smallest tenant unit, provides cross-cluster resource isolation capabilities. Members in a workspace can create projects in authorized clusters and invite users to participate in project collaboration.

This section describes how to control access permissions at the platform level in KubeSphere, including the management of users and platform roles.

ifeval::["{file_output_type}" == "html"]
For access control at the cluster level, please refer to link:../07-cluster-management/09-cluster-settings/04-cluster-roles/[Cluster Roles].
For access control at the workspace level, please refer to link:../08-workspace-management/06-workspace-settings/04-workspace-roles/[Workspace Roles].
For access control at the project level, please refer to link:../08-workspace-management/08-projects/02-project-roles[Project Roles].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
For access control at the cluster level, please refer to the "Cluster Roles" chapter in the *KubeSphere Cluster Management Guide*.
For access control at the workspace level, please refer to the "Workspace Roles" chapter in the *KubeSphere Workspace and Project Management Guide*.
For access control at the project level, please refer to the "Project Roles" chapter in the *KubeSphere Workspace and Project Management Guide*.
endif::[]

ifeval::["{file_output_type}" == "pdf"]
== Product Version

This document applies to KubeSphere v4.2.0.

== Target Audience

This document is primarily intended for the following readers:

* KubeSphere Users

* Delivery Engineers

* Operations Engineers

* Support Engineers


== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Change Description

|01
|{pdf_releaseDate}
|First official release.
|===
endif::[]