---
title: "View Image Builder Details"
keywords: "Kubernetes, {ks_product}, Image Builder, View Image Builder Details"
description: "Describes how to view image builder details."
weight: 03
---


:ks_permission: **Application Workloads View**
:ks_navigation: **Image Builders**


This section describes how to view image builder details.


== Prerequisites


:relfileprefix: ../../../

include::../../../_custom/projectManagement/projectManagement-prer-requiredPermission_v42.adoc[]

:relfileprefix: ./



== Steps

include::../../../_custom/workspaceManagement/workspaceManagement-oper-openWorkspacePage.adoc[]

+

include::../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../_custom/projectManagement/projects-oper-dropdownList.adoc[]
+

include::../../../_custom/projectManagement/imageBuilders/imageBuilders-oper-openDetailsPage.adoc[]

+

. On the image builder details page, view the resource attributes of the image builder in the **Attributes** area.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

include::../../../_custom/projectManagement/imageBuilders/imageBuilders-para-imageName.adoc[]

|Project
|The project to which the image builder belongs.

include::../../../_custom/projectManagement/imageBuilders/imageBuilders-para-type.adoc[]

|Builder Image
|The image address, name, and tag of the builder itself.

|Image Name
|The namespace and name of the target image generated by the build.

include::../../../_custom/projectManagement/services/services-para-codeRepositoryURL.adoc[]

|Pull Policy
|The policy for pulling base images or dependency images during the build process.

* **Prefer local image (IfNotPresent)**: Preferentially uses images stored on the node by the container runtime.

* **Always pull image (Always)**: Always attempts to pull images from the image registry.

* **Use local image only (Never)**: Uses only images stored on the node by the container runtime.

|Remote Trigger
|The URL used to trigger an image build. Sending an HTTP GET request to this address will trigger an image build. The address shown here is only accessible from within the cluster. To access it from outside the cluster, you need to perform the following steps:

* Expose the **s2ioperator-trigger-service** service externally via NodePort or LoadBalancer.

* Send an HTTP GET request to the external access address of the **s2ioperator-trigger-service** service and the same path to trigger an image build.

include::../../../_custom/projectManagement/imageBuilders/imageBuilders-para-creationTime.adoc[]

|Creator
|The user who created the image builder.
|===
--

. On the image builder details page, click the **Run Records** tab to view the run records of the image builder.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Last Build Environment
|The build environment used for the last image build.

* For building images from source code, it displays the builder image, code repository URL, and the branch where the code resides.

* For building images from artifacts, it displays the builder image, artifact file name, and artifact file size.

|Run Records
|The run records of the image builds, showing the sequence number, status, image name, start time, and last message.

Click image:/images/ks-qkcp/zh/icons/log.svg["log",18,18] next to the sequence number to view the image build logs.
|===
--

. On the image builder details page, click the **Resource Status** tab to view the pod running status of the image builder.
+
--
include::../../../_custom/clusterManagement/nodes/nodes-para-podList.adoc[]
--

. On the image builder details page, click the **Image Artifacts** tab to view the container images generated by the build.
+
--
The **Image Artifacts** tab displays the name, size, pull command, and release time of the container images.
--

. On the image builder details page, click the **Environment Variables** tab to view the container environment variables of the image builder.

. On the image builder details page, click the **Events** tab to view the resource events of the image builder.