---
title: "Edit Persistent Volume Information"
keywords: "Kubernetes, {ks_product}, Cluster Management, Storage, Persistent Volume Claim, Persistent Volume, Edit Persistent Volume Information"
description: "Describes how to edit the information of a persistent volume."
weight: 12
---

:ks_permission: **Persistent Volume Claim Management**
:ks_navigation: **Storage > Persistent Volume Claims**


This section describes how to edit the information of a persistent volume.

You can edit the alias and description of a persistent volume. KubeSphere does not support editing the name of a persistent volume.


== Prerequisites


:relfileprefix: ../../../../

include::../../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./



== Steps

include::../../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../../_custom/clusterManagement/persistentVolumes/persistentVolumes-oper-openListPage.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the persistent volume you want to operate on, and then select **Edit Information** from the drop-down list.

. In the **Edit Information** dialog box, set the alias and description for the persistent volume, and then click **OK**.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Alias
|The alias of the persistent volume. Different persistent volumes can have the same alias.
// The alias can only contain Chinese characters, letters, numbers, and hyphens (-). It cannot start or end with a hyphen (-) and can be up to 63 characters long.

|Description
|The description of the persistent volume. The description can contain any characters, up to a maximum of 256 characters.
|===
--