---
title: "Uninstall KubeSphere Only"
keywords: "Kubernetes, {ks_product}, Uninstall KubeSphere Only"
description: "Describes how to uninstall KubeSphere."
weight: 01
---

This section describes how to uninstall KubeSphere. The Kubernetes running in the current cluster will not be uninstalled.

// Warning
include::../../../../_ks_components/admonitions/warning.adoc[]

* Although this operation will not uninstall Kubernetes, if the business running in the current cluster uses features provided by KubeSphere, this operation may still cause business interruption.

* This operation cannot be undone. Please perform this operation with caution.

include::../../../../_ks_components/admonitions/admonEnd.adoc[]


== Prerequisites

include::../../../_custom/installationAndUpgrade/installationAndUpgrade-prer-backUpData.adoc[]

== Uninstall Extensions

. Log in to any cluster node and execute the following command to view the extensions installed in the cluster.
+
[,bash]
----
kubectl get installplan
----

. Uninstall the specified extension or all extensions.


* Uninstall a specified extension.
+
--
[,bash]
----
kubectl delete installplan {InstallPlan Name}
----
[.admon.note,cols="a"]
|===
|Note

|
You can obtain the `InstallPlan Name` of the extension using the command from the first step.
|===

If the following information is displayed, the extension has been successfully uninstalled.

[,bash]
----
installplan.kubesphere.io "{InstallPlan Name}" deleted
----
--

* Uninstall all extensions.
+
--
[,bash]
----
kubectl delete installplan --all
----

The output should be similar to the following:

[,bash]
----
installplan.kubesphere.io "devops" deleted
installplan.kubesphere.io "dmp" deleted
installplan.kubesphere.io "gatekeeper" deleted
installplan.kubesphere.io "gateway" deleted
installplan.kubesphere.io "kubefed" deleted
installplan.kubesphere.io "metrics-server" deleted
installplan.kubesphere.io "network" deleted
installplan.kubesphere.io "openpitrix" deleted
installplan.kubesphere.io "opensearch" deleted
installplan.kubesphere.io "springcloud" deleted
installplan.kubesphere.io "storage-utils" deleted
installplan.kubesphere.io "tower" deleted
installplan.kubesphere.io "vector" deleted
installplan.kubesphere.io "whizard-alerting" deleted
installplan.kubesphere.io "whizard-auditing" deleted
installplan.kubesphere.io "whizard-events" deleted
installplan.kubesphere.io "whizard-logging" deleted
installplan.kubesphere.io "whizard-monitoring" deleted
installplan.kubesphere.io "whizard-notification" deleted
installplan.kubesphere.io "whizard-telemetry" deleted
installplan.kubesphere.io "whizard-telemetry-ruler" deleted
----

Execute the following command again. If `No resources found` is displayed, all extensions have been uninstalled.

[,bash]
----
kubectl get installplan
----
--


== Uninstall ks-core

Before uninstalling ks-core, ensure all extensions in the cluster have been uninstalled, meaning the command `kubectl get installplan` returns `No resources found`.

. Execute the following command to uninstall ks-core.
+
[,bash]
----
helm del -n kubesphere-system ks-core
----

. Execute the following command. If the result is empty (as shown below), KubeSphere has been successfully uninstalled.
+
--
[,bash]
----
root@xxx:~# helm list -n kubesphere-system
NAME    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
----
--