---
title: "Install Extensions"
keywords: "Kubernetes, {ks_product}, Installation, Extensions, Multi-cluster"
description: "Describes how to install extensions."
weight: 01
---

This section describes how to install extensions.

ifeval::["{file_output_type}" == "html"]
For information on how to access, configure, and use each extension, refer to link:../../11-use-extensions/[Extensions User Guide].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
For information on how to access, configure, and use each extension, refer to the *KubeSphere Extensions User Guide*.
endif::[]

== Prerequisites

ifeval::["{file_output_type}" == "html"]
You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../05-users-and-roles/01-users/[Users] and link:../../05-users-and-roles/02-platform-roles/[Platform Roles].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to the *KubeSphere User and Role Management Guide*.
endif::[]

== Installation Steps

include::../../_custom/extensionInstall/install-all-extensions_v42.adoc[]