---
title: "Uninstall Extensions"
keywords: "Kubernetes, {ks_product}, Uninstall, Force Uninstall, Extension"
description: "Describes how to uninstall an extension."
weight: 05
---

This section describes how to uninstall an extension.

You can uninstall an extension on its details page in the Extensions Center.

For extensions configured with a cluster agent, the cluster agent will be uninstalled first, followed by the extension itself.

== Prerequisites

You must have the **platform-admin** role within the KubeSphere platform. For more information, please refer to link:../../05-users-and-roles/01-users/[Users] and link:../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

include::../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center** to go to the Extensions Center page.
. Click the name of an installed extension to go to its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] below the extension icon, and select **Uninstall**.
. Enter the name of the extension, then click **OK** to begin the uninstall process.