---
title: "Extension Management"
keywords: "Kubernetes, {ks_product}, Extension Management"
description: "Describes how to install and manage extensions."
weight: 06
icon: "/images/docs/common/docs.svg"
layout: "second"
---



This section describes how to install, configure, upgrade, and uninstall extensions.

KubeSphere extensions are application forms built on KubeSphere LuBan, designed to extend and enhance KubeSphere's product capabilities, further meeting various business needs of enterprises. After KubeSphere installation, only the core components are enabled by default. It is recommended that you install extensions from the Extensions Center to fully utilize KubeSphere's features.


ifeval::["{file_output_type}" == "pdf"]

== Product Version

This document applies to KubeSphere v4.2.0.

== Target Audience

This document is primarily intended for the following readers:

* KubeSphere Users

* Delivery Engineers

* Operations Engineers

* Support Engineers


== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Description of Changes

|01
|{pdf_releaseDate}
|First official release.
|===

endif::[]