---
title: "Log in and Enter a Federated Project"
keywords: "Kubernetes, {ks_product}, Project Management, Web Console, Federated Project"
description: "Introduces how to log in and enter a federated project."
weight: 01
---



This section describes how to log in to the KubeSphere web console and enter a federated project.


== Prerequisites

* The KubeSphere platform must have the **Federated Application Management** extension installed and enabled.

* You need to obtain the username and password of a federated project member.


== Method 1

. Log in to the KubeSphere web console and enter your workspace.

. In the left navigation pane, click **Federated Projects** to enter the Federated Projects page.

. On the Federated Projects page, click the name of a federated project to enter it.

== Method 2

. Log in to the KubeSphere web console.

. Click **Component Dock > Federated Projects** in the upper-right corner to enter the Federated Projects page.

. On the Federated Projects page, select a workspace to view its corresponding federated projects.

. Click the name of a federated project to enter it.