// :ks_include_id: c4e995deeaff4c618dca0b53432cab70
. On the workload details page, view the resource attributes of the workload in the **Attributes** area. Click the attribute bar to collapse this area.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Cluster
|The cluster to which the workload belongs.

|Project
|The project to which the workload belongs.

|Application
|The name of the application to which the workload belongs. You can create an application that contains multiple services, each corresponding to a workload.

|Creation Time
|The creation time of the workload.

|Update Time
|The update time of the workload.

|Creator
|The user who created the workload.
|===
--

. On the workload details page, click **Events** to view events related to the workload.
+
--
include::../clusterManagement-para-eventsTab.adoc[]
--

. On the workload details page, click **Edit Configuration** to modify the configuration of the workload. For more information, refer to "Editing Workload Settings".

. On the workload details page, click **Revision Records** to view the modification information of the workload.
+
--
* Select a revision record from the dropdown list to view its serial number, creation time, and configuration file. The KubeSphere system automatically assigns a serial number to each revision record and retains up to 10 records.

* The **Configuration File** area displays the differences between the current configuration file and the previous revision's configuration file. Click image:/images/ks-qkcp/zh/icons/chevron-down.svg[chevron-down,18,18] to display the configuration file differences vertically, and click image:/images/ks-qkcp/zh/icons/chevron-right.svg[chevron-right,18,18] to display them horizontally.
--

. In the **Container Status Management** area, view the container information and container replica information within the workload.
+
====
* If the workload contains multiple containers, click the container name to select other containers from the dropdown list, then view the resource status, container replicas, and other information for that container below.

* Under **Container Resource Status**, view the current container's environment variables, port information, and mounted volumes.

* Under **Container Replica List**, view information about the container replicas.
+
--
* Click **Container Logs** to view the logs of the current container.

* Click **Pod Events** to view events related to the pod to which the current container belongs.

* Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] > **Terminal** to open the container terminal. You can use the container terminal to execute commands inside the container.

* Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] > **Details** to view detailed information about the pod to which the current container belongs.
--
====