---
title: "Create Network Policy"
keywords: "Kubernetes, {ks_product}, Cluster Management, Network, Network Policy, Create Network Policy"
description: "Introduces how to create a network policy."
weight: 01
---

:ks_permission: **Cluster Network Resource Management**
:ks_navigation: **Network > Network Policy**

This section describes how to create a network policy.

[.admon.note,cols="a"]
|===
|Note

|After creating a network policy on the Cluster page, you can enter the workspace to which the network policy's project belongs, click **Service Networking > Project Network Policies**, select the project, and then view the network policies of that project.

|===

[.admon.attention,cols="a"]
|===
|Attention

|The Project Network Policies page only supports viewing network policies. If you need to create or manage network policies, please go to the Cluster's "Network Policies" page.
|===

== Prerequisites

:relfileprefix: ../../../../
* {empty}
include::../../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./


* The KubeSphere platform needs to have the **KubeSphere Network** extension installed and enabled.


== Steps

include::../../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../../../_ks_components/oper-clickCreate.adoc[]

+

. In the **Create Network Policy** dialog box, configure the network policy's configuration file, then click **OK**.
+
--
* Click image:/images/ks-qkcp/zh/icons/upload-dark-white.svg[upload-dark-white,18,18] in the upper right corner to upload a configuration file.

* Click image:/images/ks-qkcp/zh/icons/download-dark-white.svg[download-dark-white,18,18] in the upper right corner to download a configuration file.

// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

KubeSphere currently does not support creating network policies through a graphical interface. For specific parameters of the network policy configuration file, please refer to the link:https://kubernetes.io/zh/docs/concepts/services-networking/network-policies/[Kubernetes official documentation].

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]

After creation, the network policy will be displayed in the network policy list.
--