---
title: "Reset Built-in Rule Groups"
keywords: "Kubernetes, {ks_product}, Cluster Management, Monitoring and Alerting, Alert Management, Rule Groups, Delete Rule Groups"
description: "Describes how to reset built-in rule groups."
weight: 08
---

// :ks_permission: **Rule Group Management**
// :ks_menu: **Platform Management > WizTelemetry Global Monitoring**
:ks_navigation: **Global Alerting > Built-in Rule Groups**

This section describes how to reset built-in rule groups.

[.admon.note,cols="a"]
|===
|Note

|
KubeSphere only supports resetting built-in rule groups and does not support resetting custom rule groups.
|===

[.admon.warning,cols="a"]
|===
|Warning

|
Rule groups cannot be recovered after being reset. Please perform this operation with caution.
|===




== Prerequisites

You need to have the **platform-admin** role in the KubeSphere platform. For more information, please refer to link:../../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].


== Steps

include::../../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

+

include::../../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../../_ks_components/oper-navigate.adoc[]

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the rule group you want to reset, and then select **Reset** from the dropdown list.

. In the **Reset Rule Group** dialog box, click **OK**.