---
title: "Edit Custom Resources"
keywords: "Kubernetes, {ks_product}, Cluster Management, Custom Resource Definition, Edit Custom Resources"
description: "Describes how to edit custom resources."
weight: 03
---

:ks_permission: **Custom Resource Definition Management**
:ks_navigation: **Custom Resource Definitions**


This section describes how to edit custom resources.


== Prerequisites


:relfileprefix: ../../../

include::../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./



== Steps

include::../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../_custom/clusterManagement/crds/crds-oper-openDetailsPage.adoc[]

+

. On the **Custom Resource Definitions** tab, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the custom resource you want to edit, and then select **Edit YAML** from the drop-down list.

. In the **Edit YAML** dialog box, modify the YAML settings of the custom resource, and then click **OK**.
+
--
* Click image:/images/ks-qkcp/zh/icons/upload-dark-white.svg[upload-dark-white,18,18] in the upper right corner of the dialog box to upload a local YAML configuration file.

* Click image:/images/ks-qkcp/zh/icons/download-dark-white.svg[download-dark-white,18,18] in the upper right corner of the dialog box to download the YAML configuration file to your local machine.

// Note
include::../../../../_ks_components/admonitions/note.adoc[]

You need to modify the settings of the custom resource according to the Custom Resource Definition specification and the API provided by the controller. For more information, please refer to the link:https://kubernetes.io/zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/[Kubernetes official documentation].

include::../../../../_ks_components/admonitions/admonEnd.adoc[]
--