---
title: "Configuring Cloud Storage Devices"
keywords: "Kubernetes, {ks_product}, Installation, Preparation, Persistent Storage, Cloud Storage Devices"
description: "Describes how to configure cloud storage devices for a KubeSphere cluster in a production environment."
weight: 01
---


This section describes how to configure cloud storage devices for KubeSphere in a production environment.

You can create API keys in a cloud environment and configure KubeSphere to use these keys to interface with the cloud environment via the Container Storage Interface (CSI). When users create volumes on the KubeSphere platform and mount them to pods, KubeSphere will automatically create storage devices in the cloud environment for the pods to use. The following uses QingCloud as an example to describe the specific operations. For operations in other cloud environments, please refer to the user guide of the cloud environment or contact your cloud service provider.


== Prerequisites

You need to obtain a QingCloud account and ensure the account balance is sufficient to create the required storage devices. For more information, please visit the link:https://www.qingcloud.com/[QingCloud official website].


== Steps

. Log in to the link:https://www.qingcloud.com/[QingCloud] console, click the username in the upper right corner of the page, and then select **API Keys** from the dropdown list.

. On the **API Keys** page, click **Create**.

. In the **Create API Key** dialog box, set the name for the key, and then click **Submit**.

. In the pop-up dialog box, download the private key file to your local machine.
+
--
// Warning
include::../../../../../_ks_components/admonitions/warning.adoc[]

KubeSphere will use this private key to interface with the cloud storage devices. Please keep this private key file safe to avoid user data leakage.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

. Obtain the ID of the API key from the API key list.

. Log in to the cluster node used to perform the KubeSphere installation operation and execute the following command to create the storage plugin configuration file:
+
--
// Bash
include::../../../../../_ks_components/code/bash.adoc[]

vi csi-qingcloud.yaml

include::../../../../../_ks_components/code/codeEnd.adoc[]
--

. Add the following information to the configuration file and save the file for use during the subsequent KubeSphere installation:
+
--
// YAML
include::../../../../../_ks_components/code/yaml.adoc[]

config:
  qy_access_key_id: "<key ID>"
  qy_secret_access_key: "<access key>"
  zone: "<zone ID>"
sc:
  isDefaultClass: true

include::../../../../../_ks_components/code/codeEnd.adoc[]

Replace the following parameters with actual values:

[%header,cols="1a,4a"]
|===
|Parameter |Description

|<key ID>
|The ID of the API key.

|<access key>
|The private key text of the API key.

|<zone ID>
|
The availability zone ID of the cloud environment. The availability zone ID determines the region where KubeSphere will create the storage devices. The correspondence between ID values and availability zones is as follows:

* **sh1a/sh1b**: Shanghai 1 Zone-A/Shanghai 1 Zone-B

* **pek3a/pek3b/pek3c/pek3d**: Beijing 3 Zone-A/Beijing 3 Zone-B/Beijing 3 Zone-C/Beijing 3 Zone-D

* **gd2a/gd2b**: Guangdong 2 Zone-A/Guangdong 2 Zone-B

* **ap2a**: Asia Pacific 2 Zone-A
|===

The above configuration file only includes the mandatory parameters. To set other parameters, please refer to link:https://github.com/kubesphere/helm-charts/tree/master/src/test/csi-qingcloud#configuration[QingCloud CSI Configuration].
--