---
title: "Edit Platform Role Information"
keywords: "Kubernetes, {ks_product}, Platform Management, Access Control, Platform Roles, Edit Platform Role Information"
description: "Describes how to edit platform role information."
weight: 04
---

:ks_menu: **Users and Role Management**
:ks_permission: **Role Management**
:ks_navigation: **Platform Roles**

This section describes how to edit platform role information.

You can edit the alias and description of platform roles created by users. KubeSphere does not support editing built-in platform roles, nor does it support editing the names of platform roles.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform. For more information, please refer to link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Steps

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. In the left navigation pane, select **Platform Roles**.
. To the right of the platform role you want to operate on, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18], then select **Edit Information** from the dropdown list.
. In the **Edit Information** dialog box, set the alias and description for the platform role, then click **OK**.
+
[%header,cols="1a,4a"]
|===
|Parameter |Description

include::../../../_custom/platformManagement/accessControl/platformRoles/platformRoles-para-aliasDescription.adoc[]
|===