---
title: "View Workspace Monitoring Overview"
description: "Describes how to view monitoring information on the workspace overview page."
weight: 02
---

:ks_permission: **Monitoring Viewing**
:ks_navigation: **Overview**

This section describes how to view monitoring information on the workspace overview page.

== Prerequisites

:relfileprefix: ../../../../../
* {empty}
include::../../../../../_custom/workspaceManagement/workspaceManagement-prer-requiredPermission_v4.adoc[]

:relfileprefix: ./

* The **WizTelemetry Monitoring** extension must be installed and enabled on the KubeSphere platform.

== Steps

include::../../../../../_custom/workspaceManagement/workspaceManagement-oper-openWorkspacePage.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

. Click **Resource Usage** to view the usage of physical resources and application resources in the workspace.
+
--
[%header,cols="1a,4a"]
|===
|Area |Description

|Physical Resources
|CPU and memory usage of the workspace in the specified cluster.

|Application Resources
|The number of Deployments, StatefulSets, DaemonSets, Jobs, CronJobs, Persistent Volume Claims, etc., created by the workspace in the specified cluster.
|===

include::../../../../../../_ks_components/oper-selectTimeRange.adoc[]

include::../../../../../../_ks_components/oper-Autorefresh.adoc[]

include::../../../../../../_ks_components/oper-refreshData.adoc[]

* Click the **Cluster** dropdown in the upper right corner to view data for a specific cluster.

* Click the line charts in **Physical Resources** and **Application Resource Usage** to view detailed information about resource usage over time. Select a project, click OK to view resource usage information for a specific project.
--

. Click **Usage Ranking** to view the resource usage of projects within the workspace.
+
--
* Click the **Cluster** dropdown in the upper left corner of the list to view data for a specific cluster.

* Click the dropdown above the list to sort projects by CPU usage, memory usage, pod count, outbound traffic, or inbound traffic.

* Click image:/images/ks-qkcp/zh/icons/sort-ascending.svg[sort-ascending,18,18]/image:/images/ks-qkcp/zh/icons/sort-descending.svg[sort-descending,18,18] above the list to sort in ascending/descending order.

include::../../../../../_custom/clusterManagement/clusterStatus/clusterStatus-oper-exportJsonData.adoc[]
--

. Click **Cluster Information** to view the total and used amounts of CPU, memory, and disk for clusters authorized to the workspace, as well as the total number of pods that can be created and the number already created on the cluster.
+
--
// Note
include::../../../../../../_ks_components/admonitions/note.adoc[]

By default, a maximum of 110 pods can be created per cluster node.

include::../../../../../../_ks_components/admonitions/admonEnd.adoc[]
--