---
title: "Configure Feishu Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Configure Feishu Notification"
description: "Introduces how to configure Feishu notification."
weight: 02
---

:ks_navigation: **Notification > Notification Channels**
// :ks_permission: **Platform Settings Management**


This section describes how to configure Feishu notification.

The Feishu notification feature supports sending notifications to users in the following two ways:

* **Session Settings**: Use a Feishu app to send notifications to specific users or departments.

* **Group Bot Settings**: Use a Feishu bot to send notifications to specific group chats.


== Prerequisites

* The KubeSphere platform needs to have the **WizTelemetry Notification** extension installed and enabled.

* You need to obtain the access parameters for the app or group bot from the Feishu platform in advance. For more information, refer to the link:https://open.feishu.cn/document/ukTMukTMukTM/uITNz4iM1MjLyUzM[Feishu Developer Documentation].


== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Feishu** tab, configure the Feishu notification parameters, and then click **OK**.
+
====
* Session Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|App ID
|The App ID of the Feishu app.

|App Secret
|The App Secret of the Feishu app.

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sessionId.adoc[]
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper right corner of the **Feishu** tab, click the toggle switch to set the Feishu notification feature to **Enabled**.