---
title: "Configure DingTalk Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Configure DingTalk Notification"
description: "Describes how to configure DingTalk notification."
weight: 03
---

:ks_navigation: **Notification > Notification Channels**
// :ks_permission: **Platform Settings Management**

This section describes how to configure DingTalk notification.

The DingTalk notification feature supports sending notifications to users in the following two ways:

* **Session Settings**: Use a DingTalk app to send notifications to specific users or departments.

* **Group Chat Bot Settings**: Use a DingTalk bot to send notifications to specific group chats.

== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the access parameters for the app or group chat bot from the DingTalk platform in advance. For more information, refer to link:https://open.dingtalk.com/document/orgapp-server/how-to-call-apis[DingTalk Developer Documentation].

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **DingTalk** tab, configure the DingTalk notification parameters, and then click **OK**.
+
====
* Session Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|App Key
|The AppKey of the DingTalk app.

|App Secret
|The App Secret of the DingTalk app.

|Chat ID
|The Chat ID to receive notifications. Click **Add** to set multiple Chat IDs.
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====


. In the upper right corner of the **DingTalk** tab, click the toggle switch to set the DingTalk notification feature to **Enabled**.