---
title: "Configure WeCom Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Configure WeCom Notification"
description: "Introduces how to configure WeCom notification."
weight: 04
---


:ks_navigation: **Notification > Notification Channels**
// :ks_permission: **Platform Settings Management**


This section describes how to configure WeCom notification. After configuration, you can receive notification messages through WeCom sessions or group bots.


== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the access parameters for the application or group bot from the WeCom platform in advance. For more information, refer to link:https://developer.work.weixin.qq.com/document/path/90664[WeCom Developer Documentation].


== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **WeCom** tab, set the WeCom notification parameters, and then click **OK**.
+
====
* Session Settings > Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Corp ID
|The Corp ID of your enterprise on WeCom.

|Agent ID
|The Agent ID of the WeCom application.

|Secret
|The Secret of the WeCom application.
|===
--

* Session Settings > Receiver Settings
+
--
Set the User ID, Department ID, or Tag ID to receive notifications. Click **Add** to set multiple IDs.
--

* Group Bot Settings > Group Bot Settings
+
--
Webhook URL: The webhook address of the WeCom group bot.
--

* Group Bot Settings > Receiver Settings
+
--
Set the User ID or user mobile number to receive notifications. Click **Add** to set multiple IDs and mobile numbers.
--


include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper right corner of the **WeCom** tab, click the toggle switch to set the WeCom notification function to **Enabled**.