---
title: "Set Up Slack Notifications"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set Up Slack Notifications"
description: "Describes how to set up Slack notifications."
weight: 05
---


:ks_navigation: **Notification > Notification Channels**
// :ks_permission: **Platform Settings Management**


This section describes how to set up Slack notifications.


== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the application access parameters from the Slack platform in advance. For more information, refer to the link:https://api.slack.com/messaging/webhooks#create_a_webhook[Slack Developer Documentation].


== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Slack** tab, configure the Slack notification parameters, and then click **OK**.
+
====
* Server Settings
+
--
Configure the token used to access the Slack application.
--

* Slack Channel Settings
+
--
Configure the Slack channel to receive notifications. Click **Add** to configure multiple Slack channels.
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper right corner of the **Slack** tab, click the toggle switch to set the Slack notification function to **Enabled**.