---
title: "Set Webhook Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set Webhook Notification"
description: "Describes how to set up Webhook notification."
weight: 06
---

:ks_navigation: **Notification > Notification Channels**
// :ks_permission: **Platform Settings Management**

This section describes how to set up Webhook notification.

== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the access parameters for the Webhook in advance. For more information, please contact your Webhook administrator.

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Webhook** tab, set the Webhook notification parameters, and then click **OK**.
+
====
* Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Webhook URL
|The access URL for the Webhook.

|Authentication Type
|The authentication type for the Webhook.

* **No Authentication**: No authentication is required.

* **Bearer Token**: Use a URL Bearer token for authentication. If you select this type, you need to further set the token used for authentication.

* **Basic Authentication**: Use a username and password for authentication. If you select this type, you need to further set the username and password used for authentication.

|Skip TLS Verification (Insecure)
|Whether to skip TLS verification when calling the Webhook.
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper right corner of the **Webhook** tab, click the toggle switch to set the Webhook notification function to **Enabled**.