---
title: "Enable Log Collection"
description: "Describes how to modify the configuration of the extension to enable the log collection feature."
weight: 01
---

This section describes how to modify the configuration of the "WizTelemetry Logging" extension to enable the log collection feature.

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The **WizTelemetry Logging** extension needs to be installed and enabled on the KubeSphere platform.

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center**.
. Click the installed **WizTelemetry Logging** extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] under the extension icon and select **Extension Configuration**.
. In the extension configuration file, set the **logsidecar-injector.enabled** parameter to **true**, then save the file.
+
--
[,yaml]
----
logsidecar-injector:
  enabled: true
----

[.admon.note,cols="a"]
|===
|Note

|
Since the job controlling the update of this parameter only runs on the host cluster, if you want to enable or disable the disk log collection feature only for certain member clusters, setting logsidecar-injector.enabled in the member cluster configuration alone will not take effect. Each time this parameter is modified, the parameter in the host cluster must also be modified to trigger the update.

For example, to disable the log collection feature for a specific member cluster, you only need to set logsidecar-injector.enabled: false in that member cluster's configuration, and then set logsidecar-injector.updateVersion: 1 in the host cluster's configuration. For subsequent similar operations, you only need to update the logsidecar-injector.updateVersion to trigger the update.
|===
--

. After enabling, go to the **Project Management > Project List** page in the workspace. The **Log Collection** field will appear in the list header, with a default value of **Disabled**.