---
title: "启用日志收集"
description: "介绍如何修改扩展组件的配置，以启用日志收集功能。"
weight: 01
---

本节介绍如何修改“WizTelemetry 日志”扩展组件的配置，以启用日志收集功能。


== 前提条件

* 您需要在 KubeSphere 平台具有 **platform-admin** 角色。有关更多信息，请参阅link:../../../../../05-users-and-roles/01-users/[用户]和link:../../../../../05-users-and-roles/02-platform-roles/[平台角色]。

* KubeSphere 平台需要安装并启用 **WizTelemetry 日志**扩展组件。

== 操作步骤

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. 点击**扩展中心**。
. 点击已安装的 **WizTelemetry 日志**扩展组件，进入组件详情页。
. 点击组件图标下的image:/images/ks-qkcp/zh/icons/more.svg[more,18,18]，选择**扩展组件配置**。
. 在扩展组件配置文件中，将 **logsidecar-injector.enabled** 参数设置为 **true**，然后保存文件。
+
--
[,yaml]
----
logsidecar-injector:
  enabled: true
----

[.admon.note,cols="a"]
|===
|说明

|
由于控制此参数更新的 job 只会在 host 集群运行，因此如果想仅开启或关闭某些 member 集群的落盘日志收集功能，只设置 member 集群的 logsidecar-injector.enabled 不会生效。每次修改此参数都需要同时修改 host 集群的参数，以此来触发参数更新。

例如，当需要将某个 member 集群的日志收集功能关闭，只需要在该 member 集群的配置中设置 logsidecar-injector.enabled: false，然后在 host 集群的配置中设置 logsidecar-injector.updateVersion: 1。后续再进行同样操作只需要更新 logsidecar-injector.updateVersion，即可触发更新。
|===
--

. 启用后，进入企业空间的**项目管理 > 项目列表**页面，在列表表头将显⽰**日志收集**字段， 默认值为**已禁用**。