---
title: "Edit Log Receiver Settings"
keywords: "Kubernetes, {ks_product}, Cluster Management, Cluster Settings, Log Receiver, Edit Log Receiver Settings"
description: "Describes how to edit log receiver settings."
weight: 04
---

:ks_permission: ** cluster-admin **
:ks_navigation: **Logging > Log Receivers**


This section describes how to edit log receiver settings.


== Prerequisites

:relfileprefix: ../../../../../

* {empty}
include::../../../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./

* A log receiver has been added.


== Steps

include::../../../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Log Receivers** page, click **Container Logs**, **Resource Events**, **Audit Logs**, or **Notification History**, then click the name of a log receiver in the list to open its details page.

+

. On the log receiver details page, click **Operation > Edit**.

. In the dialog box that pops up, modify the settings of the log receiver, then click **OK**.
+
--
include::../../../../../_custom/clusterManagement/logReceivers/logReceivers-para-addLogReceiver.adoc[]

[.admon.attention,cols="a"]
|===
|Note

|
After modification, ensure that the `endpoints` under each component configuration in the extension configuration of the **WizTelemetry Platform Service** are consistent with the modified service address, so that the KubeSphere platform can correctly query log data. For more information, please refer to the details page description of the "WizTelemetry Platform Service" extension in the Extensions Center.

|===
--