---
title: "Log Query"
keywords: "Kubernetes, {ks_product}, Cluster Management, Query Container Logs"
description: "Describes how to query container logs."
weight: 03
---

:ks_permission: ** cluster-admin **
:ks_navigation: **Logging > Log Query**


This section describes how to query container logs.

Container logs: Logs obtained from the standard output of containers. The content of container logs is determined by the applications running in the containers.

KubeSphere supports querying container logs within the user's permission scope, whether as a regular user or a cluster administrator.

== Query Logs as a Regular User

=== Prerequisites

The **WizTelemetry Logging** extension must be installed and enabled on the KubeSphere platform.

=== Query Container Logs

. Log in to the KubeSphere web console.

. Click **Component Dock > WizTelemetry Observability Platform**.

+

include::../../../../../_ks_components/oper-navigate.adoc[]

. On the Log Query page, set search criteria to query logs.
+
--
* If there are multiple clusters, click the **Cluster** dropdown list to query logs in a specific cluster.

* Click the search box, set search criteria, and then press **Enter** to view logs that meet specific conditions. You can set multiple search criteria simultaneously.

* On the query results page, you can view the time distribution chart of the logs. Click on the histogram to switch to the log list for that time period. Click image:/images/ks-qkcp/zh/icons/start-dark.svg[start-dark,18,18]/image:/images/ks-qkcp/zh/icons/stop-dark-white.svg[stop-dark-white,18,18] to start/stop real-time data refresh. Click the **Log Export** dropdown list to choose to export container logs in ascending or descending order. Click the time under **Refresh Frequency** to select the data refresh frequency.

* Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper right corner of the query results list to customize the information displayed in the list.

* Click a log entry in the query results to view detailed information about the log.
--

== Query Logs as a Cluster Administrator

=== Prerequisites

:relfileprefix: ../../../../

* {empty}
include::../../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./

* The **WizTelemetry Logging** extension must be installed and enabled on the KubeSphere platform.

=== Query Container Logs

include::../../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

. On the Log Query page, set search criteria to query logs.

== Query Calico Logs

The "WizTelemetry Logging" extension collects Calico logs by default, including Calico pod IP allocation and release information. You can limit the search criteria to query Calico logs.

On the Log Query page, set the following search criteria to query Calico logs.

----
Project: kube-system
Pod: <node name>
Container: calico-cni
----