---
title: "日志查询"
keywords: "Kubernetes, {ks_product}, 集群管理, 查询容器日志"
description: "介绍如何查询容器日志。"
weight: 03
---

:ks_permission: ** cluster-admin **
:ks_navigation: **日志 > 日志查询**


本节介绍如何查询容器日志。

容器日志：从容器标准输出获取的日志。容器日志的内容由容器中运行的应用程序决定。

KubeSphere 支持以普通用户角色或集群管理员角色查询自身权限范围内的容器日志。


== 以普通用户角色查询日志

=== 前提条件

KubeSphere 平台需要安装并启用 **WizTelemetry 日志**扩展组件。

=== 查询容器日志

. 登录 KubeSphere Web 控制台。

. 点击**组件坞 > WizTelemetry 可观测平台**。

+

include::../../../../../_ks_components/oper-navigate.adoc[]

. 在日志查询页面，设置搜索条件查询日志。
+
--
* 如果有多个集群，点击**集群**下拉列表可查询特定集群中的日志。

* 点击搜索框，设置搜索条件，然后按 **Enter** 可查看符合特定条件的日志。您可以同时设置多个搜索条件。

* 在查询结果页面可查看日志的时间分布图，点击柱状图，切换到该时间段的日志列表。点击image:/images/ks-qkcp/zh/icons/start-dark.svg[start-dark,18,18]/image:/images/ks-qkcp/zh/icons/stop-dark-white.svg[stop-dark-white,18,18]可开启/停止实时数据刷新，点击**日志导出**下拉列表可选择正序或倒序导出容器日志，点击**刷新频率**的时间可选择数据的刷新频率。

* 在查询结果列表右上角点击image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18]可定制列表中显示的信息。

* 点击查询结果中的日志条目，查看日志的详细信息。
--

== 以集群管理员角色查询日志

=== 前提条件

:relfileprefix: ../../../../

* {empty}
include::../../../../_custom/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

:relfileprefix: ./

* KubeSphere 平台需要安装并启用 **WizTelemetry 日志**扩展组件。

=== 查询容器日志

include::../../../../_custom/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

. 在日志查询页面，设置搜索条件查询日志。

== 查询 Calico 日志

“WizTelemetry 日志”扩展组件默认收集 Calico 的日志，包含 Calico pod ip 的分配和释放信息，可限定查询条件查询 Calico 日志。

在日志查询页面，设置以下搜索条件查询 Calico 日志。

----
项目: kube-system
容器组: <node name>
容器: calico-cni
----