---
title: "启用 WizTelemetry 全局监控"
description: "介绍如何启用 WizTelemetry 全局监控。"
weight: 01
---

为了使用 WizTelemetry 全局监控的完整功能，您需要安装 WizTelemetry 平台服务、 WizTelemetry 监控、WizTelemetry 告警以及 WizTelemetry 全局监控扩展组件，并进行以下配置。

== 前提条件

* 您需要在 KubeSphere 平台具有 **platform-admin** 角色。有关更多信息，请参阅link:../../../../05-users-and-roles/01-users/[用户]和link:../../../../05-users-and-roles/02-platform-roles/[平台角色]。

* 已安装 **WizTelemetry 平台服务**、 **WizTelemetry 监控**、**WizTelemetry 告警**以及 **WizTelemetry 全局监控**扩展组件。

// * 已在**平台设置 > 许可证**页面导入 WizTelemetry 可观测平台 Pro 版或 WizTelemetry 全局监控的 license，否则，无法使用 WizTelemetry 全局监控的功能。

== 操作步骤

include::../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. 点击**扩展中心**。
. 点击已安装的组件名称，进入组件详情页。
. 点击组件图标下的image:/images/ks-qkcp/zh/icons/more.svg[more,18,18]，选择**扩展组件配置**。
+
--
**WizTelemetry 全局监控**

将扩展组件配置中的 `whizard-agent-proxy.config.gatewayUrl` 参数设置为 `http://{host_cluster_node_ip}:30990`，然后点击**确定**。

`gatewayUrl` 是 WizTelemetry 全局监控中 `whizard` Gateway 组件的对外访问地址，默认使用 NodePort 30990 端口暴露，可以使用 host 集群任一节点 IP 及 30990 端口进行配置。

示例：
[source,yaml]
----
whizard-agent-proxy:
  config:
    # set whizard gateway url，default is http://{host_cluster_node_ip}:30990
    gatewayUrl: "http://172.31.73.206:30990"
----


**WizTelemetry 平台服务**

将扩展组件配置中的 `whizard-telemetry.config.observability.enabled` 参数设置为 `true`，然后点击**确定**。

[,yaml]
----
whizard-telemetry:
  config:
    observability:
      enabled: true
      endpoint: "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902"
----

**WizTelemetry 监控**

将扩展组件配置中的 `kube-prometheus-stack.prometheus.agentMode` 参数设置为 `true`，然后点击**确定**。

[,yaml]
----
kube-prometheus-stack:
  prometheus:
    # agentMode need to be set to true when enable whizard
    agentMode: true
----

**WizTelemetry 告警**

将扩展组件配置中的 `global.rules.distributionMode` 参数设置为 `None`，然后点击**确定**。

[,yaml]
----
global:
  rules:
    # None for environment with enabled whizard
    # Member for environment with disabled whizard
    distributionMode: None
----

[.admon.attention,cols="a"]
|===
|注意

|
* 当新增集群时，请确保 WizTelemetry 全局监控、WizTelemetry 监控及 WizTelemetry 告警的集群 Agent 被选中并正常安装。

* 卸载 WizTelemetry 全局监控时，您仍需参照以上配置，将其他扩展组件的配置恢复原值。

|===
--

. 编辑完成后，从组件坞进入 WizTelemetry 可观测平台，可发现 WizTelemetry 全局监控提供的**全局监控**和**全局告警**页面均正常显示数据。