---
title: "Enable WizTelemetry Global Monitoring"
description: "Describes how to enable WizTelemetry Global Monitoring."
weight: 01
---

To use the full functionality of WizTelemetry Global Monitoring, you need to install the WizTelemetry Platform Service, WizTelemetry Monitoring, WizTelemetry Alerting, and WizTelemetry Global Monitoring extensions, and perform the following configurations.

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../../../05-users-and-roles/01-users/[Users] and link:../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The **WizTelemetry Platform Service**, **WizTelemetry Monitoring**, **WizTelemetry Alerting**, and **WizTelemetry Global Monitoring** extensions have been installed.

// * A WizTelemetry Observability Platform Pro or WizTelemetry Global Monitoring license has been imported on the **Platform Settings > License** page. Otherwise, the WizTelemetry Global Monitoring features cannot be used.

== Steps

include::../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click **Extensions Center**.
. Click the name of the installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] under the extension icon and select **Extension Configuration**.
+
--
**WizTelemetry Global Monitoring**

Set the `whizard-agent-proxy.config.gatewayUrl` parameter in the extension configuration to `http://{host_cluster_node_ip}:30990`, then click **OK**.

`gatewayUrl` is the external access address for the `whizard` Gateway component in WizTelemetry Global Monitoring. It is exposed by default using NodePort 30990. You can configure it using any host cluster node IP and port 30990.

Example:
[source,yaml]
----
whizard-agent-proxy:
  config:
    # set whizard gateway url，default is http://{host_cluster_node_ip}:30990
    gatewayUrl: "http://172.31.73.206:30990"
----


**WizTelemetry Platform Service**

Set the `whizard-telemetry.config.observability.enabled` parameter in the extension configuration to `true`, then click **OK**.

[,yaml]
----
whizard-telemetry:
  config:
    observability:
      enabled: true
      endpoint: "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902"
----

**WizTelemetry Monitoring**

Set the `kube-prometheus-stack.prometheus.agentMode` parameter in the extension configuration to `true`, then click **OK**.

[,yaml]
----
kube-prometheus-stack:
  prometheus:
    # agentMode need to be set to true when enable whizard
    agentMode: true
----

**WizTelemetry Alerting**

Set the `global.rules.distributionMode` parameter in the extension configuration to `None`, then click **OK**.

[,yaml]
----
global:
  rules:
    # None for environment with enabled whizard
    # Member for environment with disabled whizard
    distributionMode: None
----

[.admon.attention,cols="a"]
|===
|Note

|
* When adding a new cluster, ensure that the cluster Agents for WizTelemetry Global Monitoring, WizTelemetry Monitoring, and WizTelemetry Alerting are selected and installed correctly.

* When uninstalling WizTelemetry Global Monitoring, you still need to refer to the above configurations to restore the other extensions' configurations to their original values.

|===
--

. After editing, enter the WizTelemetry Observability Platform from the Component Dock. You will find that the **Global Monitoring** and **Global Alerting** pages provided by WizTelemetry Global Monitoring display data normally.