---
title: "选择 Jenkins Agent"
keywords: "Kubernetes, {ks_product}, DevOps 项目, 使用 DevOps, 流水线"
description: "介绍如何选择 Jenkins Agent。"
weight: 12
---


**agent** 部分指定整个流水线或特定阶段 (Stage) 将在 Jenkins 环境中执行的位置，具体取决于该 **agent** 部分的放置位置。该部分必须在 **pipeline** 块的顶层进行定义，但是阶段级别的使用是可选的。有关更多信息，请参阅 link:https://www.jenkins.io/zh/doc/book/pipeline/syntax/#代理[Jenkins 官方文档]。


== 内置 podTemplate

podTemplate 是一种 Pod 模板，用于创建 Agent。您可以定义在 Kubernetes 插件中使用的 podTemplate。

在流水线运行期间，每个 Jenkins Agent Pod 必须具有一个名为 **jnlp** 的容器，以便实现 Jenkins Controller 与 Jenkins Agent 之间的通信。此外，您可以在 podTemplate 中添加容器，以满足个性化需求。可选择使用自定义的 Pod YAML 来灵活控制运行时环境（Runtime），并通过 **container** 命令来切换容器。以下是相关示例。

[,json]
----
pipeline {
  agent {
    kubernetes {
      //cloud 'kubernetes'
      label 'mypod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command: ['cat']
    tty: true
"""
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
      }
    }
  }
}
----

在当前版本中，KubeSphere 内置了一类 podTemplate：**base**，并且在 Pod 中提供隔离的 Docker 环境。

您可以通过指定 Agent 的标签来使用内置 podTemplate。例如，要使用 nodejs 的 podTemplate，在创建流水线时指定标签为 **nodejs** 即可，具体参阅以下示例。

[,json]
----
pipeline {
  agent {
    node {
      label 'nodejs'
    }
  }

  stages {
    stage('nodejs hello') {
      steps {
        container('nodejs') {
          sh 'yarn -v'
          sh 'node -v'
          sh 'docker version'
          sh 'docker images'
        }
      }
    }
  }
}
----


* podTemplate base
+
--
[%header,cols="1a,4a"]
|===
|名称 |类型/版本

|Jenkins Agent 标签
|base, go, java, jdk, maven, nodejs 等

|容器名称
|base

|操作系统
|Ubuntu 24.04

|Docker
|最新稳定版

|Helm
|最新稳定版

|Kubectl
|最新稳定版

|内置工具
|unzip、which、make、wget、zip、bzip2、git
|===
--