---
title: "Global Overview"
keywords: "Kubernetes, {ks_product}, Platform Management, WizTelemetry Global Monitoring, View Multi-Cluster Monitoring Data"
description: "Describes how to view monitoring overview information for multiple clusters."
weight: 01
---

:ks_navigation: **Global Monitoring > Global Overview**

This section describes how to view monitoring overview information for multiple clusters.

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, see link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The host cluster and the member clusters to be monitored need to have WizTelemetry Global Monitoring enabled.
+
--
// Note
include::../../../../../../_ks_components/admonitions/note.adoc[]

If a member cluster does not have WizTelemetry Global Monitoring enabled, WizTelemetry Global Monitoring will not be able to obtain data from that member cluster.

include::../../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]
+
--
The Overview page displays monitoring information for all clusters with WizTelemetry Global Monitoring enabled by default.

[%header,cols="1a,4a"]
|===
|Functional Area |Description

|Number of Created Resources
|Displays the number of all monitored clusters, nodes, projects, pods, Deployments, StatefulSets, DaemonSets, Jobs, CronJobs, PersistentVolumeClaims, Services, and Ingresses.

|Resource Usage
|Displays the CPU, memory, and disk usage of all nodes across all monitored clusters, and the percentage of created pods relative to the maximum number of pods that can be created. By default, each node can create up to 110 pods.

For CPU and memory, hover over image:/images/ks-qkcp/zh/icons/eye.svg[eye,18,18] to view the amount of resources reserved and limited for containers and projects.

// |Cluster Members and Cluster Roles
// |Displays the number of cluster members and cluster roles for all monitored clusters.

|Global Alerts
|Displays the number of alerts generated by global alert rule groups and the most recent alert messages. Alerts displayed here do not include those generated by cluster and project alert rule groups. Global alert rule groups are managed by platform administrators in **Global Alerts**.

Alert severity types include **Info, Warning, Important, and Critical**.

Alert status types include:

include::../../../../../_custom/clusterManagement/alerts/alerts-para-alertingStatus.adoc[]

|Pods
|Displays the number of various types of pods across all monitored clusters.

Pod status types include:

include::../../../../../_custom/clusterManagement/pods/pods-para-podStatus_overview.adoc[]

Pod QoS (Quality of Service) types include:

include::../../../../../_custom/clusterManagement/pods/pods-para-qosTypes.adoc[]

include::../../../../../_custom/clusterManagement/pods/pods-para-oomTypes.adoc[]
|===
--

. In the upper right corner of the page, click **Select Cluster** and choose the clusters you want to monitor. The Overview page will display monitoring information for the selected clusters.

. Click **Collapse Cluster List/Expand Cluster List** to hide or show the cluster list on the right.
+
--
* Click a cluster name in the cluster list to enter the monitoring overview page for that cluster.

* Click image:/images/ks-qkcp/zh/icons/row.svg[row,18,18] and image:/images/ks-qkcp/zh/icons/list_view.svg[list_view,18,18] to view cluster information in list or thumbnail format.

* Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] to enter the **Component Settings** page. For more information, see link:../02-set-alert-components/[Set Components].
--