---
title: "View Cluster Key Metrics Ranking"
keywords: "Kubernetes, {ks_product}, Multi-cluster, WizTelemetry Global Monitoring, Cluster, Key Metrics Ranking"
description: "Introduces how to sort clusters based on multi-dimensional monitoring metrics."
weight: 04
---

:ks_navigation: **Global Monitoring > Clusters**

This section describes how to sort clusters based on multi-dimensional monitoring metrics.

== Prerequisites

* You need to have the **platform-admin** role in the KubeSphere platform. For more information, refer to link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The host cluster and the member clusters to be monitored need to have WizTelemetry Global Monitoring enabled.
+
--
// Note
include::../../../../../../_ks_components/admonitions/note.adoc[]

If a member cluster does not have WizTelemetry Global Monitoring enabled, WizTelemetry Global Monitoring will not be able to retrieve data from that member cluster.

include::../../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]
+
--
View the status, node count, and other monitoring metric data for each cluster.

include::../../../../../_custom/WizTelemetry/sort-by-fields-and-order.adoc[]

* Click the search box above the list and enter keywords to search for clusters by name.

include::../../../../../../_ks_components/oper-refreshListData.adoc[]

include::../../../../../../_ks_components/oper-customizeColumns.adoc[]
--