---
title: "View Project Monitoring Details"
keywords: "Kubernetes, {ks_product}, WizTelemetry Global Monitoring, Project, Resource Usage Ranking"
description: "Describes how to view the resource usage details of a project."
weight: 11
---

:ks_navigation: **Global Monitoring > Projects**

This section describes how to view the monitoring details of a single project.

== Prerequisites

You need to have the **platform-admin** role on the KubeSphere platform. For more information, please refer to link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

include::../../../../../_custom/WizTelemetry/enter-into-WizTelemetry.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

. In the project list, click the name of a project to open its details page.

. In the upper area of the details page, view the basic information of the current project.
+
--
* Click **Manage Project** to enter the details page of the current project.
* Click image:/images/ks-qkcp/zh/icons/chevron-down.svg[chevron-down,18,18] to hide this area.
--

. Under the **Overview** tab of the details page, view the overview information of the project.
+
--
[%header,cols="1a,4a"]
|===
|Area |Description

|Resource Statistics
|The number of Deployments, StatefulSets, DaemonSets, Jobs, Services, PersistentVolumeClaims, Ingresses, and pods created in the current project.

|Real-time Resource Usage
|The real-time usage and total amount of CPU and memory for the current project; as well as PersistentVolume usage and PersistentVolume reserved quantity. Click **All** to view the PersistentVolume usage and reserved quantity for different types of storage.

Click the corresponding area to view the real-time usage percentage of that resource.

|Project Quotas
|
ifeval::["{file_output_type}" == "html"]
For more information about the parameters, please refer to link:../../../../../08-workspace-management/08-projects/05-project-quotas/03-view-project-quotas/[View Project Quotas].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
For more information about the parameters, please refer to the "Project Quotas" chapter in the *KubeSphere Workspace and Project Management Guide*.
endif::[]

|Project Alerts
|The number of alerts generated by global alert rule groups in the current project. Alerts displayed here do not include those generated by cluster and project alert rule groups. Global alert rule groups are managed by platform administrators in **Global Alerting**.

Alert severity types include **Info, Warning, Important, and Critical**.

Alert status types include:

include::../../../../../_custom/clusterManagement/alerts/alerts-para-alertingStatus.adoc[]

|Pods
|The number of various types of pods in the current project.

Pod status types include:

include::../../../../../_custom/clusterManagement/pods/pods-para-podStatus_overview.adoc[]

Pod QoS (Quality of Service) types include:

include::../../../../../_custom/clusterManagement/pods/pods-para-qosTypes.adoc[]

include::../../../../../_custom/clusterManagement/pods/pods-para-oomTypes.adoc[]
|===
--

. Click the **Workloads** or **Pods** tab on the details page to view the monitoring information of all workloads or pods in the project.
+
--
include::../../../../../_custom/WizTelemetry/sort-by-fields-and-order.adoc[]

* Click the search box above the list and enter keywords to search for corresponding objects by name.

include::../../../../../../_ks_components/oper-refreshListData.adoc[]

include::../../../../../../_ks_components/oper-customizeColumns.adoc[]
--

. Click the **Monitoring** tab on the details page to view detailed information of monitoring metrics within a specified time range.
+
--
include::../../../../../../_ks_components/oper-selectTimeRange.adoc[]

include::../../../../../../_ks_components/oper-Autorefresh.adoc[]

include::../../../../../../_ks_components/oper-refreshData.adoc[]
--