Log in to the deployment node, navigate to the offline package directory, and obtain the node information and installation configuration files for subsequent execution of the `kk` command.

[source,bash]
----
cd offline
----

[.admon.attention,cols="a"]
|===
|Note

|The subsequent steps must be executed within the directory where the offline package is extracted (e.g., `offline`), otherwise the operation will fail.
|===


**1. Obtain Node Information: kkv4-inventory.yaml**


. Obtain the node information file.
+
====
[source,bash]
----
cp kubekey/runtime/kubekey.kubesphere.io/v1/inventories/default/default.yaml kkv4-inventory.yaml
----

Example node information:
[source,yaml]
----
apiVersion: kubekey.kubesphere.io/v1
kind: Inventory
metadata:
  name: default
  namespace: default
spec:
  groups:
    etcd:
      hosts:
      - scan-cqxbav3
      vars: null
    image_registry:
      hosts: []
      vars: null
    k8s_cluster:
      groups:
      - kube_control_plane
      - kube_worker
      hosts: null
      vars: null
    kube_control_plane:
      hosts:
      - scan-cqxbav3
      vars: null
    kube_worker:
      hosts:
      - scan-cqxbav3
      vars: null
    nfs:
      hosts: []
      vars: null
  hosts:
    scan-cqxbav3:
      connector:
        host: 172.16.0.4
        password: ""
        port: "22"
        user: root
      internal_ipv4: 172.16.0.4
      kubernetes:
        custom_labels: {}
  vars: null
status: {}
----
====

**2. Obtain Installation Configuration File: kkv4-config.json**

. Install `jq`.
+
--
On Ubuntu operating system, execute the following installation command:

[source,bash]
----
sudo apt install jq
----

If the deployment node uses a different operating system, replace **apt** with the package management tool corresponding to that operating system.
--

. Obtain the configuration file `kkv4-config.json` used during cluster installation.
+
====
[source,bash]
----
cd schema/config.json | jq '{spec: .["kubernetes.json"]}' > kkv4-config.json
----
Example configuration information:

[source,yaml]
----
{
  "spec": {
    "kubernetes": {
      "cluster_name": "cluster-01",
      "kube_version": "v1.33.3",
      "control_plane_endpoint": {
        "host": "lb.kubesphere.local",
        "port": 6443,
        "type": "local"
      }
    },
    "cri": {
      "container_manager": "containerd"
    },
    "cni": {
      "type": "calico",
      "max_pods": 110,
      "service_cidr": "10.233.0.0/18",
      "pod_cidr": "10.233.64.0/18",
      "ipv4_mask_size": 24,
      "ipv6_mask_size": 64
    },
    "image_registry": {
      "auth": {
        "registry": "dockerhub.kubekey.local",
        "username": "admin",
        "password": "Harbor12345",
        "insecure": true
      }
    },
    "storage_class": {
      "local": {
        "enabled": true,
        "default": true,
        "path": "/var/openebs/local"
      }
    }
  }
}
----
====