---
title: "Edit Member Cluster Configuration"
keywords: "Kubernetes, {ks_product}, Multi-cluster Management, Cluster, Edit Cluster Configuration"
description: "Describes how to edit member cluster configuration."
weight: 05
---

:ks_permission: **Cluster Management**

This section describes how to edit the cluster configuration of a member cluster, i.e., adjust the ks-agent configuration parameters.

In addition to configuring the cluster when adding a member cluster, you can also edit the cluster configuration after the member cluster has been added.

[.admon.note,cols="a"]
|===
|Note

|
When the KubeSphere version of the member cluster is inconsistent with the KubeSphere version of the host cluster, you cannot edit the cluster configuration. Please update to the same version before proceeding.
|===

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform.

== Steps

include::../../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]

. Click **Cluster Management**.

. On the right side of the cluster you want to operate, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18], then select **Edit Configuration** from the dropdown list.

. In the **Edit Configuration** dialog box, enter the ks-agent information, then click **OK**.