---
title: "Update kubeconfig"
keywords: "Kubernetes, {ks_product}, Multi-cluster Management, Cluster, Update kubeconfig"
description: "Describes how to update the kubeconfig information of a member cluster."
weight: 07
---


:ks_menu: **Cluster Management**
:ks_permission: **Cluster Management**


This section describes how to update the kubeconfig information of a member cluster.

After adding a member cluster to the KubeSphere platform, if the access information of the member cluster changes, you need to update the kubeconfig information of the member cluster.

// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

KubeSphere only supports editing the kubeconfig information of clusters added via direct connection, and does not support editing the kubeconfig information of clusters added via proxy connection.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]


== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform.




== Steps

include::../../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]

. Click **Cluster Management**.

. On the right side of the cluster you want to operate, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18], and then select **Update kubeconfig** from the drop-down list.

. In the **Update kubeconfig** dialog box, enter the kubeconfig information, and then click **Update**.
+
--
// Tip
include::../../../../../_ks_components/admonitions/tip.adoc[]

You can click image:/images/ks-qkcp/zh/icons/upload-dark-white.svg[upload-dark-white,18,18] to upload a kubeconfig configuration file from your local machine.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]

The KubeSphere web console of the host cluster will use the new kubeconfig information to connect to the member cluster.
--