---
title: "Set Email Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set Email Notification"
description: "Introduces how to set up email notification."
weight: 01
---

// :ks_navigation: **Notification > Notification Channels**


This section describes how to set up email notification.


== Prerequisites

The **WizTelemetry Notification** extension needs to be installed and enabled on the KubeSphere platform.

== Steps

// include::../../../../../_custom/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Log in to the KubeSphere web console.

. In the upper-right corner of the page, click the current username, and then select **Notification Settings** from the drop-down list.

. On the **Notification Settings** page, on the **Email** tab, set the email notification parameters, and then click **OK**.
+
====
* Receiver Settings
+
Enter the email address, and click **Add** to set multiple notification recipients.

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch at the top to enable email notification.