---
title: "Configure Feishu Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Configure Feishu Notification"
description: "Describes how to configure Feishu notification."
weight: 02
---

// :ks_navigation: **Notification > Notification Channels**


This section describes how to configure Feishu notification.

The Feishu notification feature supports sending notifications to users in the following two ways:

* **Session Settings**: Use a Feishu app to send notifications to specific users or departments.

* **Group Bot Settings**: Use a Feishu bot to send notifications to specific group chats.


== Prerequisites

* The KubeSphere platform needs to have the **WizTelemetry Notification** extension installed and enabled.

* You need to obtain the access parameters for the app or group bot from the Feishu platform in advance. For more information, refer to the link:https://open.feishu.cn/document/ukTMukTMukTM/uITNz4iM1MjLyUzM[Feishu Developer Documentation].


== Steps

. Log in to the KubeSphere web console.

. In the upper right corner of the page, click the current username, and then select **Notification Settings** from the drop-down list.

. On the **Notification Settings** page, on the **Feishu** tab, set the Feishu notification parameters, and then click **OK**.

+
====
* Session Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

// |App ID
// |The App ID of the Feishu app.

// |App Secret
// |The App Secret of the Feishu app.

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sessionId.adoc[]
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch above to enable Feishu notification.