---
title: "Set DingTalk Notifications"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set DingTalk Notifications"
description: "Describes how to set DingTalk notifications."
weight: 03
---

// :ks_navigation: **Notification > Notification Channels**


This section describes how to set DingTalk notifications.

The DingTalk notification function supports sending notifications to users in the following two ways:

* **Chat Settings**: Use a DingTalk application to send notifications to specific users or departments.

* **Group Robot Settings**: Use a DingTalk robot to send notifications to specific group chats.


== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the access parameters for the application or group robot from the DingTalk platform in advance. For more information, refer to link:https://open.dingtalk.com/document/orgapp-server/how-to-call-apis[DingTalk Developer Documentation].


== Steps

. Log in to the KubeSphere web console.

. Click the current username in the upper right corner of the page, and then select **Notification Settings** from the drop-down list.

. On the **Notification Settings** page, on the **DingTalk** tab, set the DingTalk notification parameters, and then click **OK**.

+
====
* Chat Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

// |App Key
// |The AppKey of the DingTalk application.

// |App Secret
// |The App Secret of the DingTalk application.

|Chat ID
|The Chat ID to receive notifications. Click **Add** to set multiple Chat IDs.
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====


. Click the **Notifications Disabled** switch at the top to enable DingTalk notifications.