---
title: "Set Slack Notifications"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set Slack Notifications"
description: "Describes how to set up Slack notifications."
weight: 05
---


// :ks_navigation: **Notification > Notification Channels**


This section describes how to set up Slack notifications.


== Prerequisites

* The **WizTelemetry Notification** extension must be installed and enabled on the KubeSphere platform.

* You need to obtain the application access parameters from the Slack platform in advance. For more information, refer to the link:https://api.slack.com/messaging/webhooks#create_a_webhook[Slack Developer Documentation].


== Steps

. Log in to the KubeSphere web console.

. In the upper right corner of the page, click the current username, and then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, on the **Slack** tab, set the Slack notification parameters, and then click **OK**.

+
====
// * Server Settings
// +
// --
// Set the token used to access the Slack application.
// --

* Slack Channel Settings
+
--
Set the Slack channel to receive notifications. Click **Add** to set multiple Slack channels.
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notifications Disabled** switch above to enable Slack notifications.