---
title: "Set Webhook Notification"
keywords: "Kubernetes, {ks_product}, Platform Settings, Notification Management, Notification Settings, Set Webhook Notification"
description: "Describes how to set up Webhook notification."
weight: 06
---

// :ks_navigation: **Notification > Notification Channels**


This section describes how to set up Webhook notification.


== Prerequisites

* The KubeSphere platform requires the **WizTelemetry Notification** extension to be installed and enabled.

* You need to obtain the access parameters for the Webhook in advance. For more information, please contact your Webhook administrator.


== Steps

. Log in to the KubeSphere web console.

. Click the current username in the upper-right corner of the page, then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, under the **Webhook** tab, set the Webhook notification parameters, then click **OK**.

+
====
* Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Webhook URL
|The access URL for the Webhook.

|Authentication Type
|The authentication type for the Webhook.

* **No Authentication**: Authentication is not required.

* **Bearer Token**: Use a URL Bearer token for authentication. If you select this type, you need to further set the token used for authentication.

* **Basic Authentication**: Use username and password for authentication. If you select this type, you need to further set the username and password used for authentication.

|Skip TLS Verification (Insecure)
|Whether to skip TLS verification when calling the Webhook.
|===
--

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notifications Disabled** switch at the top to enable Webhook notification.