---
title: "View Composed App Details"
keywords: "Kubernetes, {ks_product}, Federated Project, App, View App Details"
description: "Describes how to view app details in a federated project."
weight: 03
---

:ks_permission: **Federated Project View**
:ks_navigation: **Application Workloads > Apps**

This section describes how to view app details in a federated project.

== Prerequisites

* The **Federated Cluster App Management** extension must be installed and enabled on the KubeSphere platform.

* {empty}
include::../../../../../_custom/multi-clusterProjectManagement/projectManagement-prer-requiredPermission_v4.adoc[]

== Steps

include::../../../../../_custom/multi-clusterProjectManagement/projectManagement-oper-openProjectPage_v4.adoc[]

+

include::../../../../../../_ks_components/oper-navigate.adoc[]

+

. On the **Apps** page, click the name of an app to open its details page.

. On the app details page, view the app's resource attributes in the **Attributes** area.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

include::../../../../../_custom/multi-clusterProjectManagement/apps/apps-para-details.adoc[]

|===
--

+

include::../../../../../_custom/multi-clusterProjectManagement/apps/apps-oper-viewResourceStatus.adoc[]

+

. On the app details page, click **External Access** to view the app's external access mode.

. On the app details page, click **Traffic Management** to view the app's traffic information.
+
--
// Note
include::../../../../../../_ks_components/admonitions/note.adoc[]

* In the **Cluster** area, you can select a specific cluster where the app resides to view the app's traffic information for that cluster.

* To use the **Traffic Monitoring** feature, the KubeSphere Service Mesh extension must be installed and enabled on the KubeSphere platform, and you must enable application governance when creating the app. For more information, see link:../01-compose-an-app/[Create a Composed App].

include::../../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

. On the app details page, click **Tracing** to view the app's request tracing information.
+
--
// Note
include::../../../../../../_ks_components/admonitions/note.adoc[]

* In the **Cluster** area, you can select a specific cluster where the app resides to view the app's request tracing information for that cluster.

* To use the **Tracing** feature, the KubeSphere Service Mesh extension must be installed and enabled on the KubeSphere platform, and you must perform the following operations:

** Enable application governance when creating the app. For more information, see link:../01-compose-an-app/[Create a Composed App].

** Enable the project gateway and enable the tracing feature for the project gateway. For more information, see link:../../../../12-gateway/01-project-gateway/01-enable-a-project-gateway[Enable a Project Gateway].
include::../../../../../../_ks_components/admonitions/admonEnd.adoc[]
--