---
title: "Edit Grayscale Release Task Settings"
keywords: "Kubernetes, {ks_product}, Project Management, Grayscale Release, Edit Grayscale Release Task Settings"
description: "Describes how to edit grayscale release task settings."
weight: 06
---

:ks_permission: ** Service Mesh Management**
:ks_navigation: **Grayscale Release > Grayscale Release**


This section describes how to edit grayscale release task settings.


== Prerequisites

:relfileprefix: ../../../../
* {empty}
include::../../../../_custom/projectManagement/projectManagement-prer-requiredPermission_v42.adoc[]

:relfileprefix: ./

* The **KubeSphere Service Mesh** extension must be installed and enabled on the KubeSphere platform.

== Steps

include::../../../../_custom/workspaceManagement/workspaceManagement-oper-openWorkspacePage.adoc[]

+

include::../../../../../_ks_components/oper-navigate.adoc[]

+

include::../../../../_custom/projectManagement/grayscaleRelease/grayscaleRelease-oper-openDetailsPage.adoc[]

+

. In the **Version** area, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] in the upper-right corner of the new version, and then select **Edit** from the drop-down list.

. On the **New Version Settings** tab, click image:/images/ks-qkcp/zh/icons/chevron-up.svg[chevron-up,18,18]/image:/images/ks-qkcp/zh/icons/chevron-down.svg[chevron-down,18,18] to increase/decrease the number of pod replicas.
+
--
// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

Grayscale release does not support modifying the version number and container image of the new version.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

. Click the **Strategy Settings** tab, configure the traffic routing strategy and release strategy for the grayscale release task, and then click **OK**.
+
====
include::../../../../_custom/projectManagement/grayscaleRelease/grayscaleRelease-para-strategySettings.adoc[]

include::../../../../_custom/projectManagement/grayscaleRelease/grayscaleRelease-para-releasePolicy.adoc[]
====