---
title: "Edit Workspace Information"
keywords: "Kubernetes, {ks_product}, Access Control, Workspace, Edit Workspace Information"
description: "Describes how to edit workspace information."
weight: 03
---

:ks_permission: **Workspace Management**

This section describes how to edit workspace information.

You can edit the alias and description of a workspace. KubeSphere does not support editing the name of a created workspace.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform.

== Steps

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click **Workspace Management**.
. On the right side of the workspace you want to operate, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18], and then select **Edit Information** from the drop-down list.
. In the **Edit Information** dialog box, set the alias and description for the workspace, and then click **OK**.

+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Alias
|The alias of the workspace.
// The alias can contain any characters, with a maximum length of 63 characters.

|Description
|The description of the workspace. The description can contain any characters, with a maximum length of 256 characters.

|===
--