---
title: "产品简介"
description: "介绍 KubeSphere 及 v4.2 的核心特性。"
weight: 01
---

link:https://kubesphere.com.cn/kse/[KubeSphere]，是基于 Kubernetes 的分布式多租户商用云原生操作系统。在开源能力的基础上，在多云集群管理、微服务治理、应用管理、可观测等多个核心业务场景进行功能延伸。各功能实现高度模块化，满足不同场景的业务需求。以强大的企业级云原生底座，完善的专家级解决方案和服务支持，赋能企业数字化转型和规模化运营。

自 KubeSphere v4.0 起，引入扩展机制，推出了全新的架构：**KubeSphere LuBan**，它构建在 link:https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/[Kubernetes] 之上，支持高度可配置和可扩展。KubeSphere 在 KubeSphere LuBan 云原生可扩展开放架构的基础之上，能轻松实现应用的上下游联动、随时随地集成各类优质扩展组件，并提供无缝融合的业务能力与高度一致的产品体验。


== 新特性

KubeSphere v4.2 是一个包含了众多核心特性的重要版本，聚焦四大核心领域的改进与增强，具体涵盖以下方面：

[discrete]
=== 全新 UI 设计与产品体验优化

重构界面设计，简化操作路径，提升交互效率，助力用户更高效地管理各类资源。

* 页面框架优化：顶部导航栏新增全局视角切换，整合平台级管理功能。侧边导航栏常驻展示，支持资源快速切换与搜索，提升操作流畅性。
* 快捷访问功能：支持自定义集群、企业空间及扩展组件的访问入口，个性化界面提升操作效率。
* 工作负载创建流程简化：企业空间新增工作负载模板，减少层级并预置参数，让创建更迅速便捷。
* 扩展组件调用升级：工作负载详情页集成统一的扩展组件调用机制，通过弹窗操作关联资源，保持页面连贯性。
* Debug 体验增强：详情页直接展示并调试容器及副本，故障排查更高效。

[discrete]
=== 扩展组件全面可插拔

该版本进一步优化了扩展机制、提升了系统架构的灵活性。通过引入更多扩展点、深度解耦功能模块、支持组件按需加载、提供灵活的配置机制及完善的生命周期管理体系，全面解决了模块耦合度高、无法独立更新、交付周期长等关键问题，大幅提升了平台的灵活性、可维护性与持续交付能力。

核心优势：

* 敏捷交付，快速响应：支持功能模块的独立升级与发布，显著缩短新功能上线与问题修复的周期，提升整体交付效率。
* 架构灵活，按需扩展：提供丰富的扩展点与组件配置选项，满足多样化业务需求，支持平台能力的持续演进。
* 精准贴合业务场景：模块化设计使功能可组合、可裁剪，助力企业快速适配不同应用场景与使用习惯。
* 增强运维效能：简化运维流程，降低平台管理成本，提升系统稳定性与可控性。

[discrete]
=== 场景化特性大幅度提升

[discrete]
==== 边缘计算能力全面增强

EdgeWize 边缘计算平台 v3.1.0 同时发布，带来三大核心功能升级：

* 运维能力增强：支持 KubeEdge 集群平滑迁移，通过 OTA 支持边缘节点的 KubeEdge/Docker 自动安装，显著提升系统稳定性与维护效率，让企业运维更省心。
* 云边协同：云边协同解决了云端与边缘设备网络隔离、通信受限等难题，通过高效安全的数据通道，实现数据与业务的无缝流转，助力企业释放边缘智能价值。
* AI 相关基础能力迁移：无缝支持多样化 AI 场景，推动边缘智能化升级。

[discrete]
==== 可观测平台重磅升级

WizTelemetry 可观测平台 v2.0 新增链路追踪与网络可观测两大核心功能，助力用户快速排查性能问题，掌控全链路运行状态，显著提升运维效率。

* 链路追踪（Tracing）：基于 OpenTelemetry 构建，支持服务拓扑自动生成、链路耗时与错误率分析，快速定位调用瓶颈。
* 网络可观测：实时生成四层网络与七层服务拓扑，结合 RED 指标与 HTTP 请求日志，深入掌握服务间通信与性能表现。

[discrete]
=== 产品优化

[discrete]
==== 网络隔离优化

网络功能升级优化，四大特性助力企业网络管理更安全、更高效！

* 新增“项目网络策略”只读展示：用户可直观查看企业空间和项目视角下的网络策略，快速排错，提升运维效率。
* 解耦“项目网络隔离”与“白名单”：支持多种隔离场景，灵活配置网络策略，增强安全性和可控性。
* 新增企业空间/项目出站流量限制：补全双向管控，满足企业安全规范，提高可靠性。
* 优化白名单配置流程：支持企业空间筛选，简化操作，减少选择困扰。

[discrete]
==== 应用商店优化

支持将系统仓库中的应用一键同步至应用商店。

针对中小型企业及开源用户，此功能跳过繁琐的审核与上架流程，快速将应用注入商店，极大简化操作路径，提升部署效率。大型企业则保留原有流程，满足严格权限与管控需求。

此优化兼顾不同企业场景，提供灵活便捷的应用管理体验，助力用户高效部署应用。
