---
title: "Application Scenarios"
description: "Introduces the application scenarios of KubeSphere."
weight: 03
---

KubeSphere is suitable for the following scenarios.

== Resource Quantification and Operations

Multi-department resource management often imposes significant pressure on operations teams. For the operations department, tasks such as calculating the resource utilization rates of various business lines and assessing the reasonableness of their resource usage require substantial time and effort. KubeSphere provides multi-dimensional and multi-perspective resource quantification and statistics, making resource data clear at a glance.

== Multi-level Permission Control

Efficient collaboration among different business lines within a company has always been a persistent challenge. How infrastructure operations, application operations, and business development personnel can work closely together through a platform while achieving permission isolation has become a core requirement of organizational structure. KubeSphere offers a "separation of powers" user permission system, reasonably distributing the three major permission perspectives—platform administrator, cluster operations, and application operations—to facilitate departmental collaboration.

== Intelligent Elastic Operations

Excessive waste of basic resources can impose additional operational costs on enterprises. Effectively analyzing the reasonableness of resource usage and performing efficient elastic resource management under different scenarios have also become challenges for operations personnel. KubeSphere provides intelligent recommendations for business resources, featuring periodic analysis and one-click application. It also supports custom metric-based elastic scaling, empowering intelligent operations.

== One-stop Cloud Native Transformation

Many enterprises encounter difficulties in technology selection when transitioning to cloud-native. How to achieve integrated DevOps operations, cloud-native microservices governance, cloud-edge collaboration, AI artificial intelligence, and observability in a cloud-native context—the selection of various technical solutions and their operations pose significant challenges for enterprises. KubeSphere integrates industry best practices, offering a highly graphical and consistent user experience to help enterprises transition to cloud-native at a low cost.