---
title: "Application Scenarios"
description: "Introduces the application scenarios of KubeSphere."
weight: 03
---

KubeSphere is suitable for the following scenarios.

== Resource Quantification and Operations

Multi-department resource management often places enormous pressure on operations teams. For the operations department, calculating the resource utilization of each business line and assessing the reasonableness of that utilization requires significant time and effort. KubeSphere provides multi-dimensional, multi-angle resource quantification and statistics, making resource data clear at a glance.

== Multi-level Permission Control

Efficient collaboration between different business lines within a company has always been a persistent challenge. How infrastructure operations, application operations, and business developers can work closely together through a platform while achieving permission isolation has become a core requirement of organizational structure. KubeSphere provides a "separation of powers" user permission system, reasonably distributing the three major permission perspectives of platform administrator, cluster operations, and application operations to promote departmental collaboration.

== Intelligent Elastic Operations

Excessive waste of basic resources incurs additional operational costs for enterprises. Effectively analyzing the reasonableness of resource usage and performing efficient resource elasticity management in different scenarios have also become challenges for operations personnel. KubeSphere provides intelligent recommendation solutions for business resources, featuring periodic analysis and one-click application. It also supports custom metric-based elastic scaling, empowering intelligent operations.

== One-stop Cloud Native Transformation

Many enterprises face technical selection difficulties when transitioning to cloud native. How to achieve integrated DevOps operations, cloud-native microservices governance, cloud-edge collaboration, AI artificial intelligence, and observability under cloud native. The selection of various technical solutions and their operations cause significant trouble for enterprises. KubeSphere integrates industry best practices, providing a highly graphical and consistent user experience to help enterprises move towards cloud native at low cost.