---
title: "Cluster Management"
keywords: "Kubernetes, {ks_product}, Cluster Management"
description: "Introduces how to manage resources in a cluster."
weight: 07
icon: "/images/docs/common/docs.svg"
layout: "second"
---

This document describes how to manage all resources in a single or multiple clusters as a cluster member.

KubeSphere supports the management of multiple clusters. Each cluster can be authorized to multiple workspaces, and each workspace can contain multiple projects.
// As a multi-tenant system, KubeSphere supports role-based access control for users at the platform, cluster, workspace, and project levels.

ifeval::["{file_output_type}" == "pdf"]
== Product Version

This document applies to KubeSphere v4.2.0.

== Intended Audience

This document is primarily intended for the following readers:

* KubeSphere Users

* Delivery Engineers

* Operations Engineers

* Post-sales Engineers


== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Description of Changes

|01
|{pdf_releaseDate}
|First official release.
|===
endif::[]