---
title: "View User List"
keywords: "Kubernetes, {ks_product}, Access Control, User, View User List"
description: "Describes how to view the user list."
weight: 02
---

:ks_menu: **User and Role Management**
:ks_navigation: **Users**
:ks_permission: **User View**

This section describes how to view the user list.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform. For more information, refer to link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].


== Steps

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. In the left navigation pane, select **Users**.
+
--
* The user list provides the following information:
+
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Username
|The name of the user.

|Status
|The current status of the user.

* **Active**: The user's current status is normal.

* **Pending**: The system is creating the user.

* **Disabled**: The user is disabled by the platform administrator and cannot log in to the KubeSphere web console.

* **Login Restricted**: The user has failed to log in 10 consecutive times within 10 minutes and is prohibited from logging in to the KubeSphere web console for 10 minutes.

|Platform Role
|The role of the user on the KubeSphere platform.

|Last Login
|The time when the user last logged in to the KubeSphere platform.
|===


* Click the search box above the list and enter a keyword to search for users by name.

include::../../../../_ks_components/oper-refreshListData.adoc[]

include::../../../../_ks_components/oper-customizeColumns.adoc[]
--