---
title: "Edit User Information"
keywords: "Kubernetes, {ks_product}, Access Control, User, Edit User Information"
description: "Describes how to edit user information."
weight: 04
---

:ks_menu: **User and Role Management**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section describes how to edit user information.

You can edit a user's alias, email, platform role, and description. KubeSphere does not support editing the username of a created user.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform. For more information, see link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Steps

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. In the left navigation pane, select **Users**.
. On the right side of the user you want to operate on, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18], and then select **Edit** from the dropdown list.
. In the **Edit User** dialog box, set the user's information, and then click **OK**.

+
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Alias
|The alias of the user.
// The alias can contain any characters, with a maximum length of 63 characters.

|Email
|The email address of the user. The email address can be used to log in to the KubeSphere web console.

|Platform Role
|The role of the user on the KubeSphere platform. The platform role determines the user's permissions in KubeSphere.

|Description
|The description of the user. The description can contain any characters, with a maximum length of 256 characters.
|===