---
title: "Change User Password"
keywords: "Kubernetes, {ks_product}, Access Control, User, Change User Password"
description: "Describes how to change a user password."
weight: 06
---

:ks_menu: **User and Role Management**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section describes how to change a user password.

== Change the Current User's Password

. Log in to the KubeSphere web console.

. In the upper-right corner of the page, click the current username, and then select **User Settings** from the drop-down list.

. Click the **Password Settings** tab to change the password of the current user.
+
The password must contain at least one digit, one lowercase letter, one uppercase letter, and one special character (~!@#$%^&*()-_=+\|[{}];:'",<.>/? or space), and be 8 to 64 characters in length.

== Change Another User's Password

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. In the left navigation pane, select **Users**.
. In the user list, click the name of a user to open its details page.
. On the user details page, click **Operation > Change Password**.
. In the **Change Password** dialog box, set a new password and re-enter it, and then click **OK**.
+
The password must contain at least one digit, one lowercase letter, one uppercase letter, and one special character (~!@#$%^&*()-_=+\|[{}];:'",<.>/? or space), and be 8 to 64 characters in length.