---
title: "Set Password Expiration"
keywords: "Kubernetes, {ks_product}, Access Control, User, Password Expiration"
description: "Introduces how to set password expiration."
weight:  08
---

:ks_navigation: **Configuration > Secret**

This section describes how to set password expiration to enforce periodic password changes and provide reminders before passwords expire.

== Prerequisites

You need to be a member of a cluster and have the **cluster-admin** role within that cluster.

== Steps

. Log in to the KubeSphere web console as a user with the **cluster-admin** role and enter your cluster.

+

include::../../../../_ks_components/oper-navigate.adoc[]

. Search for `io.kubesphere.config.platformconfig.security`.

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the Secret, then select **Edit Settings** from the dropdown list.

. In the **Edit Settings** dialog box, click image:/images/ks-qkcp/zh/icons/pen-light.svg[pen-light,18,18] to modify the value of each field. Then click **OK**.
+
--
[source,yaml]
----
passwordPolicy:
  expireEnabled: false
  maxAgeDays: 90
  reminderDays: 7
----

[%header,cols="1a,4a"]
|===
|Parameter |Description

|`expireEnabled`
|Whether to enable the password expiration feature, which forces periodic password changes.

|`maxAgeDays`
|If password expiration is enabled, the maximum validity period for a password is 90 days.

|`reminderDays`
|If password expiration is enabled, the system will start reminding the user 7 days before the password expires.

// |`forceChangeOnExpire`
// |Whether to force a password change upon expiration. If both `expireEnabled` and `forceChangeOnExpire` are `true`, a password change will be forced once the password expires.
|===
--