---
title: "Enable and Disable Users"
keywords: "Kubernetes, {ks_product}, Access Control, User, Enable and Disable Users"
description: "Introduces how to enable and disable users."
weight: 10
---

:ks_menu: **Users and Role Management**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section describes how to enable and disable users.

A disabled user cannot log in to the KubeSphere web console.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform. For more information, please refer to link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Enable and Disable a Single User

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. Select **Users** from the left navigation pane.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the user you want to operate on, and then select **Enable** or **Disable** from the dropdown list.

== Batch Enable and Disable Users

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. Select **Users** from the left navigation pane.
. Select the checkboxes on the left of the users you want to operate on, and then click **Enable** or **Disable** at the top of the list.