---
title: "Delete Users"
keywords: "Kubernetes, {ks_product}, Access Control, User, Delete User"
description: "Describes how to delete users."
weight: 15
---

:ks_menu: **User and Role Management**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section describes how to delete users.

== Prerequisites

You need to have the pass:a,q[{ks_permission}] permission on the KubeSphere platform. For more information, see link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Delete a Single User

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. Select **Users** from the left navigation pane.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the user you want to delete, and then select **Delete** from the dropdown list.
. In the **Delete User** dialog box, enter the user's name and click **OK**.

== Delete Users in Batches

include::../../../_custom/platformManagement/platformManagement-oper-logIn.adoc[]
+
. Click pass:a,q[{ks_menu}].
. Select **Users** from the left navigation pane.
. Select the checkboxes to the left of the users you want to delete, and then click **Delete** above the list.
. In the **Batch Delete Users** dialog box, enter the user names and click **OK**.
+
include::../../../../_ks_components/admonitions/note.adoc[]
Please use half-width commas (,) and spaces to separate multiple names.
include::../../../../_ks_components/admonitions/admonEnd.adoc[]